# Generated by Django 5.0.4 on 2024-05-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='publication date')),
                ('duration', models.DurationField(verbose_name='duration')),
            ],
        ),
    ]
