# Generated by Django 5.0.4 on 2024-05-12 22:06

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(storage=storages.backends.s3.S3Storage(bucket_name='brycenall-bucket', location='media/', secret_key=None, verify=False), upload_to=''),
        ),
    ]
