# Generated by Django 5.0.4 on 2024-05-12 22:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_video_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='duration',
        ),
        migrations.AddField(
            model_name='video',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
