# Generated by Django 5.0.4 on 2024-05-14 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_file_video_source_rename_name_video_title_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsletterSignupForm',
        ),
    ]
